spring:
  application:
    name: register

---
server:
  port: 8761
spring:
  profiles: dev1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

logging:
  file: ${spring.application.name}1.log

---
server:
  port: 8762
spring:
  profiles: dev2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
logging:
  file: ${spring.application.name}2.log

---
server:
  port: 8761
spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.54.30:8761/eureka/,http://172.18.54.29:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
logging:
  file:
    max-history: 7
logging.file: /home/apps/logs/register.log

---

server:
  port: 8761
spring:
  profiles: dev3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

logging:
  file: ${spring.application.name}1.log

---
server:
  port: 8762
spring:
  profiles: dev4
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
logging:
  file: ${spring.application.name}2.log

---