---
spring:
  profiles : dev
security:
  oauth2:
    domain: http://192.168.19.202:8830/se

eureka:
  client:
    service-url:
      defaultZone: http://192.168.19.21:8761/eureka,http://192.168.19.21:8762/eureka
    register-with-eureka: false

logging:
  level:
    root: info
    org.springframework.security: debug
#    de.codecentric: trace
---
spring:
  profiles : test

security:
  oauth2:
    domain: http://192.168.19.22:8840/se
eureka:
  client:
    service-url:
      defaultZone: http://192.168.19.21:8761/eureka,http://192.168.19.21:8762/eureka
    register-with-eureka: false

logging:
  level:
    root: info
  file:
    max-history: 7
logging.file: ${spring.application.name}/${spring.application.name}.log

---
spring:
  profiles : prod
  security:
    user:
      name: zhonghuilv
      password: fsdhgdfg

security:
  oauth2:
    domain: http://aiapi.huiqulx.com/se
eureka:
  client:
    service-url:
      defaultZone: http://172.18.54.30:8761/eureka,http://172.18.54.29:8761/eureka
    register-with-eureka: false
logging:
  level:
    root: info
  file:
    max-history: 7
logging.file:  /home/apps/logs/${spring.application.name}.log

