---
spring:
  profiles : dev
eureka:
  client:
    service-url:
      defaultZone: http://192.168.19.21:8761/eureka,http://192.168.19.21:8762/eureka
    register-with-eureka: false
      # 缓存注册列表
    #fetch-registry: true
logging:
  level:
    org.springframework.security: DEBUG
    springfox: DEBUG

security:
  oauth2:
    client:
      clientId: unity-client
      clientSecret: unity
  ignored: /**/noauth/**,/swagger**,/common**,/webjars/**,/common-resources/**,/v2/**,/favicon.ico,/swagger-resources/**

swagger:
  enable: true
  o-auth2:
    enable: true
    app-key: basic-api
    app-name: 基础api
    authorization-url: http://192.168.19.22:8830/se/oauth/authorize
#    authorization-url:
  apis:
    user:
      packageName: com.zhonghuilv.aitravel.basic.api.controller
      author:
        name: zhengjing
login-url: http://192.168.19.22:8840/se
---
spring:
  profiles : test
eureka:
  client:
    service-url:
      defaultZone: http://192.168.19.21:8761/eureka,http://192.168.19.21:8762/eureka

logging:
  level:
    root: info
    com.zhonghuilv: trace
  file:
    max-history: 7
logging.file: ${spring.application.name}/${spring.application.name}.log
swagger:
  enable: true
  o-auth2:
    enable: true
    app-key: basic-api
    app-name: 基础api
    authorization-url: http://192.168.19.22:8830/se/oauth/authorize
#    authorization-url:
  apis:
    user:
      packageName: com.zhonghuilv.aitravel.basic.api.controller
      author:
        name: zhengjing
security:
  oauth2:
    client:
      clientId: unity-client
      clientSecret: unity
  ignored: /**/noauth/**,/swagger**,/common**,/webjars/**,/common-resources/**,/v2/**,/favicon.ico,/swagger-resources/**

login-url: http://192.168.19.22:8840/se

---
spring:
  profiles : prod
eureka:
  client:
    service-url:
      defaultZone: http://172.18.54.30:8761/eureka,http://172.18.54.29:8761/eureka

##不知道为啥生产oauth 少了ribbon的过滤器
login-url: http://aiapi.huiqulx.com/se

logging:
  level:
    root: info
  file:
    max-history: 7
logging.file: /home/apps/logs/${spring.application.name}.log


swagger:
  enable: true
  o-auth2:
    enable: true
    app-key: basic-api
    app-name: 基础api
    authorization-url: http://aiapi.huiqulx.com/se/oauth/authorize
#    authorization-url:
  apis:
    user:
      packageName: com.zhonghuilv.aitravel.basic.api.controller
      author:
        name: zhengjing
security:
  oauth2:
    client:
      clientId: unity-client
      clientSecret: unity
  ignored: /**/noauth/**,/swagger**,/common**,/webjars/**,/common-resources/**,/v2/**,/favicon.ico,/swagger-resources/**